spring.application.name=payment-worker

spring.datasource.url=jdbc:postgresql://postgres:5432/payments
spring.datasource.username=payments
spring.datasource.password=payments
spring.jpa.hibernate.ddl-auto=validate

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=payment-worker
spring.kafka.consumer.auto-offset-reset=earliest
